name: Build AR Image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build with Maven/Jib and push to the
        env:
          AR_HOST: ${{ secrets.AR_HOST }}
          AR_REPO: ${{ secrets.AR_DIRECTORY }}
          IMG_NAME: ${{ secrets.IMG_NAME }}
          IMG_TAG: ${{ secrets.IMG_TAG }}
        run: mvn clean package com.google.cloud.tools:jib-maven-plugin:2.8.0:build -Dimage=${AR_HOST}${AR_REPO}${IMG_NAME}:${IMG_TAG} -DskipTests
