name: Deploy container image to Cloud Run

on: workflow_dispatch

env:
  AR_HOST: ${{ secrets.AR_HOST }}
  AR_DIRECTORY: ${{ secrets.AR_DIRECTORY }}
  IMG_NAME: ${{ secrets.IMG_NAME }}
  IMG_TAG: ${{ secrets.IMG_TAG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${RUN_SERVICE} --image ${AR_HOST}${AR_DIRECTORY}${IMG_NAME}:${IMG_TAG} \
            --region ${{RUN_REGION}} \
            --add-cloudsql-instances ${SQL_CONN} \
            --set-env-vars INSTANCE_CONNECTION_NAME=${SQL_CONN} \
            --set-env-vars CLOUD_SQL_CONNECTION_NAME=${SQL_CONN} \
            --set-env-vars DB_NAME=${SQL_DB} \
            --set-env-vars DB_USER=${SQL_DB_USER} \
            --set-env-vars DB_PASS=${SQL_DB_PASS} \
            --set-env-vars DB_HOST=${SQL_PRIVATE_IP} \
            --set-env-vars DB_PORT="5432" \
            --vpc-connector=${VPC_CONN} \
            --allow-unauthenticated









jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build with Maven/Jib and push to the
        env:
          AR_HOST: ${{ secrets.AR_HOST }}
          AR_DIRECTORY: ${{ secrets.AR_DIRECTORY }}
          IMG_NAME: ${{ secrets.IMG_NAME }}
          IMG_TAG: ${{ secrets.IMG_TAG }}
        run: mvn clean package com.google.cloud.tools:jib-maven-plugin:2.8.0:build -Dimage=${AR_HOST}${AR_DIRECTORY}${IMG_NAME}:${IMG_TAG} -DskipTests
